### ISSUE TITLE
listing filesystems should show more information

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-cli#101]
such as: created date, mount points, amount of data on the fs.

We just list the name right now, and it looks pretty spartan.

**Comment by mulkieran** [comment]
@agrover We already export the devnode() on the D-Bus, should we be reporting that?

**Comment by agrover** [comment]
@mulkieran the /dev/dm-X devnode? I'd rather have people use the symlink under /dev/stratis (once #682 is merged), so maybe we can show that instead..

**Comment by mulkieran** [comment]
Showing the symlink is a stratisd issue first. The problem is that the symlinks are only synthesized in the source that makes them. So a refactoring is necessary to synthesize them outside of that context.

**Comment by agrover** [comment]
Also, what its path in `/dev/stratis` is, for better discoverability and cut-n-pastability.

**Comment by agrover** [comment]
In looking to provide the symlink, because of the implementation it's kind of hard. StratFilesystem doesn't know its own name (or uuid), and doesn't know its pool's name either.

D-Bus Filesystem API methods know their pool's name, so we could implement a call to some devlinks function from there, or we could synthesize it entirely in the cli. It really depends how confident we are that these links are not going to change with any frequency.

**Comment by agrover** [comment]
fixed by #185
