### ISSUE TITLE
pool create fails with 4: entity not found

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-cli#112]
I've tried grepping for "entity not found" and am not seeing it anywhere. The pool create actually seems to succeed -- repeating it fails with "blockdev already belongs to pool foo", dm devices are created, but nothing present under /dev/stratis.
```
[agrover@fedora-devel ~]$ stratis --propagate pool create p1 /dev/vdc
Traceback (most recent call last):
  File "/usr/bin/stratis", line 32, in <module>
    main()
  File "/usr/bin/stratis", line 29, in main
    return run()(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/stratis_cli/_main.py", line 39, in the_func
    result.func(result)
  File "/usr/lib/python3.6/site-packages/stratis_cli/_actions/_top.py", line 63, in create_pool
    raise StratisCliRuntimeError(rc, message)
stratis_cli._errors.StratisCliRuntimeError: 4: entity not found
```

**Comment by mulkieran** [comment]
This really seems like a stratisd bug. If all the dm devices are created then that leaves you with a limited region in which to fail.

```
        let (uuid, pool) = StratPool::initialize(&dm, name, blockdev_paths, redundancy, force)?;

        let name = Name::new(name.to_owned());
        devlinks::pool_added(&name)?;
```

What about the metadata save? "entity" seems like such an XML-y sort of word.

**Comment by agrover** [comment]
incremental info: grepping around, this looks like it's coming from io::error, ErrorKind NotFound.

**Comment by mulkieran** [comment]
I think this is covered by https://github.com/stratis-storage/stratisd/issues/766 and #118. It's pretty easy to believe that, due to xfs missing, the MetadataVol is not created.

By that point, the blockdevs have already been claimed and most of the dm-devices have been constructed, which matches the situation described here.
