### ISSUE TITLE
Convert D-Bus stratisd error code to string

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-cli#118]
In `StratisCliRuntimeError.__str__()`, convert self.rc into a human-friendly representation. For example, when creating a pool whose name matches an existing pool, we currently get "2: (pool name)". This would tell the user more if it was "ALREADY_EXISTS: (pool name)", taken from _stratisd_constants.py, or even better "Already exists: (pool name)"

**Comment by mulkieran** [comment]
Related: #83.

**Comment by mulkieran** [comment]
Once #124 is merged the place to do this will be in ```get_error_msgs()``` in ```_error_reporting``` module.

**Comment by mulkieran** [comment]
Actually, the place to do this is in the StratsCliEngineError implementation.
