### ISSUE TITLE
RFE: Provide zsh completions

### ISSUE THREAD

**Issue by myllynen** [stratis-storage/stratis-cli#131]
It would be nice if zsh completions could be provided for stratis-cli.

In the past I've authored libvirt and openstack completions for zsh which both support a huge amount of subcommands and options but the completions even though supporting all of them are relatively compact so perhaps a similar type approach could be considered with stratis-cli as well (this might require some changes to the client output), I'm providing these two zsh completions here for reference:

https://sourceforge.net/p/zsh/code/ci/master/tree/Completion/Unix/Command/_libvirt
https://sourceforge.net/p/zsh/code/ci/master/tree/Completion/Unix/Command/_openstack

If you are interested to make users' life even more easier and push things further, much more intelligent completions with zsh are also possible but that naturally would require more effort, however e.g. the libvirt completions above already demonstrate how to provide smarter completions for a set of subcommands.

Thanks.

**Comment by mulkieran** [comment]
Is #106 relevant here?

**Comment by myllynen** [comment]
Yes, I think so. If you're planning changes on this area perhaps checking virsh and openstack clients for inspiration might be a good idea (in essence, both provide subcommand and options in a standard format that's pretty straightforward to parse in completion functions). Thanks.
