### ISSUE TITLE
'stratis blockdev list' command counter-intuitive

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [stratis-storage/stratis-cli#156]
I think this command has missed the mark of "ease of use" with pool name mandatory.  Please consider having "stratis blockdev list" without pool name show all block devices with pool name on each line, or some other simple variation (maybe even if a command omits 'list' you can just assume 'list'?).

Thanks.

stratis-cli-0.5.2-1.fc28.noarch

**Comment by mulkieran** [comment]
Could you please explain more fully.

What were you actually trying to do?
What was your intuition about how the CLI would work?
How was your intuition countered?

**Comment by DaveWysochanskiRH** [comment]
I was using stratis for the first time to create a filesystem on top of two physical devices.
The CLI should work as I explained since that is normally how storage commands work.  You should not need to specify an instance of something to get output, and certainly if you don't specify something you shouldn't get an error with a usage statement.  That runs counter to all storage commands I've ever encountered.  If you think the existing CLI is better then please defend it with real examples.  Just try 'df', 'ls', 'pvs', 'blkid', etc
