### ISSUE TITLE
'stratis blockdev' should list all blockdevs

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-cli#157]
Right now this is an invalid command and I think it returns usage info, but having it be the equivalent of 'stratis blockdev list' (once #156 is fixed) seems better.

This also applies to 'stratis pool' and 'stratis fs' commands.

**Comment by DaveWysochanskiRH** [comment]
I agree thanks for opening this one.

**Comment by DaveWysochanskiRH** [comment]
You may even want to think about listing the path to the filesystem in the 'stratis filesystem' command.  My understanding of your goals is simplified storage management.  To me this means a small cli but very intuitive and it should "just work".  You want the first impressions to be perfect if at all possible.  The smaller the number of commands the smaller the margin for error.

The was the other thing that I got hung up on - I had to manually mount the filesystem and it took a little while to figure out the path to the filesystem that was created.  Maybe this was not the intent but nothing mounted automatically (maybe another bug).

**Comment by agrover** [comment]
I think #101 is close to this, so I've added a note there for this specific piece of info.

**Comment by agrover** [comment]
fixed by https://github.com/stratis-storage/stratis-cli/pull/178 , closing
