### ISSUE TITLE
Please consider a single command to create a filesystem and pool from devices

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [stratis-storage/stratis-cli#158]
Today to my knowledge there is no existing command that will create a volume managed filesystem one line line.  Please consider whether this is something you could / would add to the cli.

Some ideas.
1. Default pool naming
2. Use default path-based naming to imply the pool.

Possibility #1:
stratis fs create /dev/stratis/mypool/myfs /dev/sdb /dev/sdc
* here the pool name is inferred in the full path to the filesystem

Possibility #2:
stratis fs create myfs /dev/sdb /dev/sdc
* This would use some default pool naming convention

**Comment by agrover** [comment]
Looking for comparisons in other implementations, ZFS requires two commands ('zpool create [devs]' followed by 'zfs create [fsnames]'. mkfs.btrfs creates a "main" volume (not sure about terminology) and then you can create subvolumes (and just use those instead of the main one, I think). LVM can create a PV, VG, and LV all in one line, I'm sure.

We'll have to think about this one a bit. The benefit would be... less typing? Better scriptability?

**Comment by DaveWysochanskiRH** [comment]
If you decide to do this, then one thing you'll have to decide is what to do about the list of devices.  A few scenarios:
a) if all devices are part of the same pool, proceed to use that pool to create the filesystem
b) if no devices are part of a pool, then maybe create a pool using a default naming scheme?
c) if some devices are part of a pool but others are not, then maybe error out (for simplicity)

**Comment by DaveWysochanskiRH** [comment]
As far as benefits these may be small but I created this because one of the goals of stratis was ease of use.  If there are users that do not care but want volume management capabilities, it's possible they will not really want to manage the pool(s) directly.

**Comment by mulkieran** [comment]
I feel that we are more likely to confuse users by incorporating this into our CLI.

We have a D-Bus API that should allow clients to interact with it and write their own sorts of commands in the manner that makes sense to them. So we would expect other users to step up and write these sorts of modifications if they desire them.

We would support them as much as possible, with advice, and, if written in Python, with our existing suite of libraries for supporting interaction with any D-Bus API, the use of which the CLI demonstrates very fully and which we plan to document as well.
