### ISSUE TITLE
Change wording of interpretation output

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-cli#169]
see https://github.com/stratis-storage/stratis-cli/issues/168#issuecomment-409768813

Avoid "you". Prefer "may" over "most likely".

@mulkieran is right that is is a cultural/tone thing. We don't want to be too "programmery", and we don't want to be too casual-seeming.

**Comment by mulkieran** [comment]
Perhaps we can move this off 1.1 as well, just like #168. Perhaps we can wait until a user requests some change.

By the way, "most likely" and "may" do actually have different meanings. If someone said "Most likely Secretariat will win the race", I might consider putting some money on him. But if someone said "Secretariat may win the race", I would be more likely to keep the money in my pocket (or lay bets all around).

**Comment by mulkieran** [comment]
I'm going to take this off 1.1. I don't think we need to worry about it too much and users are not complaining about the wording.

**Comment by mulkieran** [comment]
I'll close this entirely. The wording _is_ precise, and it doesn't go too far in claiming that something is definitely known or suggesting a remediation which in some cases might make things go badly.
