### ISSUE TITLE
Make recommendation to use wipefs to free disks more cautious

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#224]
It is certainly the case that stratisd might refuse to use a disk because it is a multipath member device. In that case, wiping the device might cause a lot of trouble. So, we can explain that ```wipefs -a``` will remove the signature, but also suggest careful consideration about whether that is the right thing to do.

**Comment by carzacc** [comment]
Obviously this also has to apply to the instructions in the man page added by  #211

**Comment by mulkieran** [comment]
> Obviously this also has to apply to the instructions in the man page added by #211

Exactly!
