### ISSUE TITLE
Work out a good set of exit values for error cases

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratis-cli#251]
Ideally we can come up with a good selection of error codes which encompasses all of the error scenarios without an overly large range of values.

**Comment by mulkieran** [comment]
See #249 for a bit of additional detail.

**Comment by mulkieran** [comment]
We define the three basics: 0, 1 for error, and 2 for parsing error and we always get them right. Given that we prefer people do not script against our CLI, that seems like it ought to be enough for the foreseeable future.
