### ISSUE TITLE
Check the error code from invocation of RUNNER in dbus tests

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#371]
We can and should do this. We rely on the implicit test of no exception raised, but checking the error code as well would be better.

**Comment by waltdisgrace** [comment]
RUNNER is equal to the the_func method defined [here](https://github.com/stratis-storage/stratis-cli/blob/f77c5fcde159b20c1ef3f084727fc818dffeb4a0/src/stratis_cli/_main.py#L36), which only ever raises an error or returns 0. This, coupled with the fact that we rely on the implicit test that no exception is raised, seems to imply that checking the error code would be redundant.

What is the reason that checking the error code would be better?

**Comment by mulkieran** [comment]
This is a bit of a tricky area, because of the fluid boundaries between the Python interpreter and the program. Right now our program only returns 0 (good), 1(error), 2(parser error), and it is correct that this method can only return a 0. All other codes returned by the program are handled by the interpreter through the raising of a SystemExit exception of some sort.

So, what I'm really saying here, is that we should somehow be checking the error code associated with the SystemExit exception. But, since right now it will always be either 2 or 1, so there is no great hurry. We actually do test it in a few cases...probably we should just be testing it in more.

**Comment by mulkieran** [comment]
For most of our tests, ```handle_err``` in the ```run()``` method is never reached, because we choose to use the ```--propagate``` flag for most tests. The reason for this is that we get more benefit from our tests this way, because we can check the resulting exception precisely. However, in most cases, we could enhance our existing tests by taking the caught exception and just passing it to the ```handle_err``` method.

Something like:

```
with self.assertRaises(SystmeExit) as final_err:
    handle_err(err)    # this is the error that we caught previously in the tests and it ought always to have been a StratisCliActionError
# assert that the exit code associated with final_err is 1.
# if it isn't, or we don't catch SystemExit then there is some kind of bug
````

You can find _some_ examples in the code where I deal with SystemExit exceptions, but I expect almost exclusively to verify that parsing errors are being handled correctly.

**Comment by mulkieran** [comment]
Related enhancement request: https://bugs.python.org/issue36691.

**Comment by mulkieran** [comment]
Probably the definition of the error codes should be in the source rather than in the tests, since we intend to extend the values in future to cover more than 0, 1, and 2.
