### ISSUE TITLE
We should run up some tests to create objects of each error type and stringify them

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#384]
The purpose would be just to make sure  that the string formatting wasn't broken in some way that pylint couldn't identify.

There are exceptions that we can't raise through normal testing of our code, but we would like them not to fail when they do get printed out.

And, we can lose a few "no cover" annotations w/out too much trouble, making our code that little bit tidier.

**Comment by waltdisgrace** [comment]
Closed by #411.
