### ISSUE TITLE
Broken pipe can cause traceback in stratis fs list

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/stratis-cli#418]
Created a over 2K filesystems on one pool, then ran: stratis fs|head, which cased a traceback. 
```
[root@stratis]# stratis fs|head
Pool Name  Name    Used     Created            Device              UUID
p1         fs382   545 MiB  Nov 19 2019 13:59  /stratis/p1/fs382   35ac31f0393f412ab9ab5f6cf1aad375
p1         fs383   545 MiB  Nov 19 2019 13:59  /stratis/p1/fs383   7754a91bd5e44ac892b875245734f72a
p1         fs384   545 MiB  Nov 19 2019 13:59  /stratis/p1/fs384   a29c5c410bc5451f84f292e56576f79f
p1         fs385   545 MiB  Nov 19 2019 13:59  /stratis/p1/fs385   59bd320515c041df877422fd926ee285
p1         fs386   545 MiB  Nov 19 2019 13:59  /stratis/p1/fs386   08f68080f5d34c8b92a4ba269e9328de
p1         fs387   545 MiB  Nov 19 2019 13:59  /stratis/p1/fs387   6387b1cd3544435988b91044e07fbb16
p1         fs388   545 MiB  Nov 19 2019 13:59  /stratis/p1/fs388   65b26fcbdd3d4d438e8e9af044ce319a
p1         fs389   545 MiB  Nov 19 2019 13:59  /stratis/p1/fs389   779667fa0e9a4faaaeddc0903f065007
p1         fs390   545 MiB  Nov 19 2019 13:59  /stratis/p1/fs390   ea1e8320836446c3be0fa99077e3fc94
stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below.

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/stratis_cli/_main.py", line 43, in the_func
    result.func(result)
  File "/usr/lib/python3.6/site-packages/stratis_cli/_actions/_logical.py", line 178, in list_volumes
    ["<", "<", "<", "<", "<", "<"],
  File "/usr/lib/python3.6/site-packages/stratis_cli/_actions/_formatting.py", line 164, in print_table
    _print_row(file, row, row_widths, column_widths, alignment)
  File "/usr/lib/python3.6/site-packages/stratis_cli/_actions/_formatting.py", line 126, in _print_row
    print("  ".join(entries), end="", file=file)
BrokenPipeError: [Errno 32] Broken pipe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/stratis", line 36, in <module>
    main()
  File "/usr/bin/stratis", line 32, in main
    return run()(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/stratis_cli/_main.py", line 59, in the_func
    handle_error(err)
  File "/usr/lib/python3.6/site-packages/stratis_cli/_error_reporting.py", line 215, in handle_error
    raise err
  File "/usr/lib/python3.6/site-packages/stratis_cli/_main.py", line 54, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['fs'] which were parsed to Namespace(func=<function LogicalActions.list_volumes at 0x7feeeb7cac80>, propagate=False) failed
```

**Comment by drckeefe** [comment]
Version of stratisd and stratis-cli used 2.0.0

**Comment by mulkieran** [comment]
We should identify this exception type in ```_error_reporting.py``` and just return a suitable message. 

It's something of a question what the message should be...we could go classic with "Broken pipe" or we could be more explanatory.

**Comment by drckeefe** [comment]
I was able to create a trace on the output of of 83 filesystems or more.  Here is a faster way to 
recreate the conditions using the sim engine.  

[root@v~]# cat pipeStratis-cli.sh 
#!/bin/bash
numFS=$1
/usr/libexec/stratisd --sim --debug 2>/dev/null &
truncate -s 1g /root/stratis.trunc1
losetup  /dev/loop1 /root/stratis.trunc1
stratis pool create p1 /dev/loop1
for i in $(seq 1 $numFS);do stratis fs create p1 fs$i;done
stratis fs|head
losetup -d /dev/loop1
rm -rf /root/stratis.trunc1
killall -9 stratisd
-----------------------------

[root@v ~]# ./pipeStratis-cli.sh 83
Pool Name  Name  Used       Created            Device            UUID                            
p1         fs8   11.77 MiB  Dec 04 2019 18:57  /stratis/p1/fs8   0a37471da8c8453daa9e9d12dfab5360
p1         fs9   11.77 MiB  Dec 04 2019 18:57  /stratis/p1/fs9   891350db6f2e47e6873f919c5c5a880b
p1         fs10  11.77 MiB  Dec 04 2019 18:57  /stratis/p1/fs10  c0ceaf03c5c34d439c0fa87582e9f9e5
p1         fs11  11.77 MiB  Dec 04 2019 18:57  /stratis/p1/fs11  267945067ac44af083620ecf9e43fb78
p1         fs12  11.77 MiB  Dec 04 2019 18:57  /stratis/p1/fs12  0e2e1f85cf9f401eb67ad23e62a79b4c
p1         fs13  11.77 MiB  Dec 04 2019 18:57  /stratis/p1/fs13  6b7443410bee4321b626e754c0fe1d57
p1         fs14  11.77 MiB  Dec 04 2019 18:57  /stratis/p1/fs14  e1620a54703d4107a9fc9bef3bc83266
p1         fs15  11.77 MiB  Dec 04 2019 18:57  /stratis/p1/fs15  d704fa389084480ab30ae934b34d3493
p1         fs16  11.77 MiB  Dec 04 2019 18:57  /stratis/p1/fs16  61df055fd87045f9b706333d2134b06b
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
./pipeStratis-cli.sh: line 13: 13192 Killed                  /usr/libexec/stratisd --sim --debug 2> /dev/null

**Comment by mulkieran** [comment]
@drckeefe, @waltdisgrace, @jbaublitz I'm breaking this into two parts. I want @waltdisgrace to complete #431 by putting in a comment, referencing issue #439 which I just wrote up, and we should be able to close out this PR in the coming week. We can the proceed with tackling #439 without too much urgency.

**Comment by jbaublitz** [comment]
For now, we seem to have a solution in #441 that should resolve this. If we ever see this bug again, we should try `sys.stdout.flush()` to see if it resolves the problem of two exceptions being raised at the same time. It may have to do with the internal `TextIOWrapper` buffering implementation in Python.
