### ISSUE TITLE
Remove all "no cover" pragmas in _errors.py

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#419]
We should be able to get complete coverage on every line in this file by extending the unittests in ```test_error_fmt.py```. Currently, we're at 94% on that file, if all remaining "no cover" pragmas are removed.

**Comment by mulkieran** [comment]
The technique here should be just to remove all the "no cover" pragmas and related comments and use the test infrastructure to bring the coverage back up to 100%.

**Comment by waltdisgrace** [comment]
Closed by: #424, #425, #433.

**Comment by mulkieran** [comment]
There's one "no cover" pragma remaining...

**Comment by waltdisgrace** [comment]
Closed by: #424, #425, #433, #437.
