### ISSUE TITLE
stratisd will need to have a service file at some time

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#48]
Apparently this will allow it to be started automatically when the CLI is invoked and when it is not already started.

**Comment by agrover** [comment]
Yes. We'll also need to drop a .conf in a special directory when we switch from using the session bus to the system bus. I previously dealt with this for https://github.com/open-iscsi/tcmu-runner so we can crib from that.

**Comment by mulkieran** [comment]
Closed by https://github.com/stratis-storage/stratisd/pull/291.
