### ISSUE TITLE
Update justbytes requirements in setup.py

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#541]
To the new version of justbytes, which was release a year ago.

**Comment by mulkieran** [comment]
Also release the Fedora packages.

**Comment by mulkieran** [comment]
We believe that the Fedora packages have been released succesfully into rawhide. The justbytes version to require is 0.14.

**Comment by mulkieran** [comment]
Would like to verify that the packages have actually landed somewhere. @drckeefe Do you know how to do this? There might be a repo tree in some well-known location or something like that.

**Comment by mulkieran** [comment]
We know that the packages made it in; because now the CLI can't build on rawhide:
https://bugzilla.redhat.com/show_bug.cgi?id=1831464.

**Comment by mulkieran** [comment]
Closed by #563

**Comment by bgurney-rh** [comment]
I added a revert PR in #568 since the blackbox tests were failing.
