### ISSUE TITLE
Add a command to use the Reports interface

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#543]
* Make the output human not machine readable; we imagine there's a library to help us here.
* We might want a separate subcommand, though, as it does not properly belong to ```daemon``` and certainly not to the other subcommands. We could call it ```report``` and that would be clear enough.

**Comment by jbaublitz** [comment]
I think we should be able to use a custom JSON encoder in the Python `json` module.

**Comment by jbaublitz** [comment]
I'm debating putting this under the `daemon` subcommand. Any objections @mulkieran? This seems like the best place to put it as it's reporting stratisd state.

**Comment by mulkieran** [comment]
I'ld rather have a separate ```report``` subcommand. It'll make it easier to call it out as unsupported except in the most minimal way.

**Comment by jbaublitz** [comment]
@mulkieran The JSON decoder by default will turn a JSON array into a list and overriding the decoding implementation for arrays is impossible. We do need this functionality unfortunately so we either have to do the remediation for this outside of the decoder or simply decode it and then encode it again back to a string format that we define as we have more flexibility while encoding than decoding. I'm not quite sure why they've allowed overriding everything but a list, but decoding and then encoding seems better suited to what we're looking to do than "decoding" a string to another string is. It makes some sense that you'd need to decode and reencode so this is probably the best option here.

**Comment by jbaublitz** [comment]
It actually looks like the json module is very opinionated and isn't very extensible for types that it recognizes even when encoding. How do you want to proceed?

**Comment by mulkieran** [comment]
Sounds iike a standup discussion!

**Comment by mulkieran** [comment]
In standup we decided just to print out the pretty-printed JSON output.
