### ISSUE TITLE
Should we hardcode /usr/bin/python3 in bin/stratis?

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-cli#55]
We don't support py2.

Hardcoding py3 would mean we don't have to talk so much about using python3 in the README. 😃

**Comment by mulkieran** [comment]
I don't know. Maybe @tasleson would have an opinion.

**Comment by tasleson** [comment]
When you package python binaries they want you to be specific, python2/3.  If you only support py3 then I would simply hard code it to python3 and be done with it IMHO.

**Comment by tasleson** [comment]
```python
#!/usr/bin/env python3
```
