### ISSUE TITLE
Add encryption example in manpage for cli

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/stratis-cli#572]
The EXAMPLES for the stratis manpage reads: 

---
       Example 1. Creating a Stratis pool

       stratis pool create mypool /dev/sdb /dev/sdc

       Example 2. Creating a filesystem from a pool

       stratis filesystem create mypool data1

---

There could be an example for creating an encrypted pool.

       Example 3. Creating an encrypted pool
       
       stratis key set --capture-key someKeyDescription

       stratis pool create --key-desc someKeyDescription mypool /dev/sdb /dev/sdc

This could be Example 2 and move creating a filesystem can be moved to Example 3.  That way
pool create examples are listed together and filesystem create are listed second.

**Comment by mulkieran** [comment]
Closed by attached PR.
