### ISSUE TITLE
Interface for cache management

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#6]
Or would pool management borrow existing devs from the cache?

Right now, it is necessary to specify devs.

**Comment by agrover** [comment]
I don't follow, once the user adds a dev to the pool as a cache device, isn't that it, from the user's perspective?

**Comment by mulkieran** [comment]
This question may go away once issues about caches in stratisd are handled.

**Comment by mulkieran** [comment]
Top-level interface for CLI now:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis --helpusage: stratis [-h] [--version] [--propagate]
               {pool,blockdev,filesystem,fs,daemon} ...

Stratis Storage Manager

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --propagate           Allow exceptions to propagate

subcommands:
  {pool,blockdev,filesystem,fs,daemon}
    pool                Perform General Pool Actions
    blockdev            Commands related to block devices that make up the
                        pool
    filesystem (fs)     Commands related to filesystems allocated from a pool
    daemon              Stratis daemon information
```

How do we fit cache management into it?

**Comment by agrover** [comment]
"cachedev" subcommand akin to "blockdev"?

**Comment by mulkieran** [comment]
blockdev top level:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis blockdev --help
usage: stratis blockdev [-h] {add,list} ...

optional arguments:
  -h, --help  show this help message and exit

subcommands:
  {add,list}
    add       Add one or more blockdevs to an existing pool
    list      List Pool Information
```

**Comment by mulkieran** [comment]
If I were a user, I would not want the step of adding the first cachedev to suddenly precipitate a big sequence of events resulting in my having a cache. I would like a second step, like "pool cache [start | stop]".

**Comment by agrover** [comment]
You think it will take a user-noticeable time to set up?

**Comment by mulkieran** [comment]
Maybe. It would make me nervous, regardless.

**Comment by agrover** [comment]
Why would the user be nervous about a newly added cache device being used immediately?

**Comment by mulkieran** [comment]
They would be nervous about the first newly added cache device meaning that they suddenly get a cache.

**Comment by agrover** [comment]
Why would the user issue a command to add a device to the cache tier if they didn't want a cache?

**Comment by mulkieran** [comment]
That's a complication I hadn't thought of.

**Comment by agrover** [comment]
We didn't add a new top-level for cache, but instead reused blockdev with add-cache and add-data subcommands. I'm not sure how relevant this issue is any more, suggest closing. @mulkieran ?

**Comment by mulkieran** [comment]
Might as well.
