### ISSUE TITLE
Distinguish cases where stratisd has actually failed to start from ones where it has failed to establish a D-Bus connection

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratis-cli#613]
If the file `/usr/lib/systemd/system/stratisd.service` is missing the stratisd service will start, but will not be able to bring up the dbus interface.  From a users perspective this could be confusing.

**Comment by mulkieran** [comment]
@lleshchi We need to decide whether we want the CLI to disambiguate between situations where stratisd is just not running, and other reasons for it not having made a D-Bus connection. If we decide we do want to disambiguate, then we'll use the psutil package to check if stratisd is running. So the solution is easy to implement; the decision is whether we want to or not. If we decide not, we'll just close the issue. If yes, then you can go ahead and implement the solution.
