### ISSUE TITLE
Document engine_state_report in stratis manpage 

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/stratis-cli#617]
I was unable to find a report_name to use when trying out "stratis report <report_name>" command.
The help output doesn't list any suggestions and the stratis manpage doesn't provide hints either

For reference, the command at this time is: 
 stratis report engine_state_report

**Comment by mulkieran** [comment]
We don't really want to document the name, because it is part of the instability of our interface that the names may change. We document that instability instead. Eventually, if we choose to move this to a more stable interface, we will document the name, and then we will support the name.

**Comment by mulkieran** [comment]
For this particular report, it's so useful, that we should probably end up moving it to a more stable interface. If we want to put in long range plans to do that, please file an issue for that, instead.
