### ISSUE TITLE
When unlocking multiple pools, if some devices can't be unlocked the error message implies that no devices were unlocked

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/stratis-cli#618]
Error message
Execution failed:
stratisd reported that it did not execute every action that it would have been expected to execute as a result of the command that you requested: stratisd reported that some existing devices are locked but no new devices were unlocked during this operation 

setup 
1. create two encrypted pools
stratis key set --capture-key foo
stratis key set --capture-key moo
stratis pool create --key-desc foo p1 /dev/sdb
stratis pool create --key-desc moo p2 /dev/sdc
2. reboot
3. Set only one key
stratis key set --capture-key foo
4. Unlock pool
stratis pool unlock
 -----------
Should the error the error message say "... but no new devices were unlocked during this operation"?  this sounds like no devices were unlock, however some were unlocked.   Is there a way for us to know if some did become unlocked.  What if the devices in the last pool that were unlock, but some devices in the first pool were not unlocked?  Would stratisd still inform the user of this error?  I'll have to test this last one.

**Comment by mulkieran** [comment]
@jbaublitz thx for picking this up.

**Comment by jbaublitz** [comment]
@mulkieran The changes here will be exclusively on the CLI side so I'm going to leave this here.
