### ISSUE TITLE
Make update_introspection_data a bit more robust in the face of existing pools and filesystems

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#661]
Right now, if it is run twice against the sim engine w/out restarting the sim engine, it fails, because the pool has already been made AND it assumes that the result is always going to represent the pool's object path.

**Comment by bgurney-rh** [comment]
I see it; when I try running `developer_tools/update_introspection_data` a second time, it outputs this traceback:
```
Traceback (most recent call last):
  File "./stratis-cli-77.77.77/developer_tools/update_introspection_data", line 172, in <module>
    main()
  File "./stratis-cli-77.77.77/developer_tools/update_introspection_data", line 139, in main
    blockdev_proxy = bus.get_object(_SERVICE, dev_object_paths[0], introspect=False)
IndexError: list index out of range
```

**Comment by bgurney-rh** [comment]
First execution:
```
(Pdb) p dev_object_paths
dbus.Array([dbus.ObjectPath('/org/storage/stratis2/2')], signature=dbus.Signature('o'))
```

Subsequent executions:
```
(Pdb) p dev_object_paths
dbus.Array([], signature=dbus.Signature('o'))
```

So, how do I distinguish between those two states?

Also, is it normal and expected for the update_introspection_data program to leave a pool and filesystem in existence after it exits?  Should these be destroyed prior to exit?

**Comment by mulkieran** [comment]
Leaving the pool and filesystem is fine, because we assume it is always running against the sim engine and stopping the sim engine will clear everything. (I'm thinking we should have a property on the D-Bus to indicate whether the engine is sim or real, but we don't have it yet, so that can't be checked.)

We want the script to be idempotent; it should be able to be run over and over again and produce the same output so long as there are no intervening mutating instructions sent to the sim engine.

The problem is that we have a minimalist idempotent API on the stratisd side: if the pool is already there, the return code is 0, but the pool_object_path is "/", the default and, as you see, dev_object_paths is also the default, which is the empty list, ```[]```. So, we'll have to find a way to get the pool object path, and the dev_object_paths even if the pool has already been constructed. That will require using GetManagedObjects and searching it to find the pool object path, etc. We'll want to use the dbus-python-client-gen functionality for GetManagedObjects the way that we do everywhere else in the CLI code. So, you'll need to add extra introspection data for the ObjectManager interface to the SPECS constant. You can look in _instrospect.py to find that data, happily it never changes.

**Comment by mulkieran** [comment]
Closing in favor of #731.
