### ISSUE TITLE
Add functionality to call the EngineStateReport via the newly introduced Manager method

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#700]
We might want to continue to do this under the report submenu.

Currently the man pages claim that all the reports are unsupported, we could change that to start a list of supported reports.
And we would invoke that report via the dedicated D-Bus API method.

**Comment by mulkieran** [comment]
Things to do:

* Update introspection data; probably best to copy it from associated PR https://github.com/stratis-storage/stratisd/pull/2371.
* Insert calls to new Manager.r4 method instead of call to the Report interface method for ```engine_state_report```. The code for this is somewhere in the actions subdirectory.
* Adjust command-line parser definition so that passing no arguments to the "report" sub-command gives the engine_state_report, i.e., make that report the default.
* Update man page to discuss supported reports and list the one report that is supported.
* Update blackbox tests as appropriate.
* Possibly update integration tests as well, but this may not be necessary.

**Comment by lleshchi** [comment]
> Things to do:
> 
> * Update introspection data; probably best to copy it from associated PR [stratis-storage/stratisd#2371](https://github.com/stratis-storage/stratisd/pull/2371).
> * Insert calls to new Manager.r4 method instead of call to the Report interface method for `engine_state_report`. The code for this is somewhere in the actions subdirectory.
> * Adjust command-line parser definition so that passing no arguments to the "report" sub-command gives the engine_state_report, i.e., make that report the default.
> * Update man page to discuss supported reports and list the one report that is supported.
> * Update blackbox tests as appropriate.
> * Possibly update integration tests as well, but this may not be necessary.

@mulkieran I somehow did not see this comment and rather than alter the parser definition, I adjusted the get_report method in _top_actions to call the correct dbus method based on the report name provided. Would adjusting the parser be more optimal? [https://github.com/lleshchi/stratis-cli/tree/engine_state_report](url)
