### ISSUE TITLE
Display information about "locked pools" by a regular CLI command

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#725]
Something like:

```
> stratis <subcommand> list locked
Pool UUID      Number of Devnodes   Encryption Info
---------------     ----------------------------   --------------------
<UUID>          1024                             Clevis
```
maybe.

**Comment by mulkieran** [comment]
@drckeefe Assigning to you for comment

**Comment by mulkieran** [comment]
This may tie into our 3.0.0 bump and removing old D-Bus API bits.

**Comment by mulkieran** [comment]
Shortly we will be exporting the information about the locked pools in a slighly more complicate fashion, we can wait until then.

**Comment by drckeefe** [comment]
This output would be useful

**Comment by mulkieran** [comment]
This will be part of the release after 3.1.0.

**Comment by mulkieran** [comment]
We will actually do it as part of 3.1.0 and stop/start pools.
