### ISSUE TITLE
Refactor _actions/_top.py into two files

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#738]
The motivation is that it has become too big. I think it should be possible to split into truly "top" operations and other operations that are per pool. We can do that after this next release.

**Comment by mulkieran** [comment]
I think it's reasonable to call the new file _pool.py.

**Comment by lleshchi** [comment]
@mulkieran I have separated the file into two. Just one question. What would you like to do with the helper functions at the top of the file which are used for both `_actions/_top.py `and `_actions/_pool.py`? I think that they could use a file of their own.
