### ISSUE TITLE
Sizes should be expressed in human units

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-cli#74]
e.g. in "stratis pool list", using a function like:
```
def sizeof_fmt(num, suffix='B'):
    for unit in ['','Ki','Mi','Gi','Ti','Pi','Ei','Zi']:
        if abs(num) < 1024.0:
            return "%3.1f%s%s" % (num, unit, suffix)
        num /= 1024.0
    return "%.1f%s%s" % (num, 'Yi', suffix)
```
(from https://stackoverflow.com/questions/1094841/reusable-library-to-get-human-readable-version-of-file-size)

**Comment by mulkieran** [comment]
That kind of thing is all covered by my library justbytes, which we should use. The function above should not be considered a good example. My, internal RH tech talk, which I could probably get permission to post externally, surely talks a bit a about this. It's called " The Computation and Representation of Address Ranges.

**Comment by agrover** [comment]
justbytes sounds ideal.
