### ISSUE TITLE
Enable basic shell scripting

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratis-cli#79]
Yes, we have an API, but I think there's an expectation that at some basic level, an admin can write a little shell script to do something in a loop, or parse output, when they need to.

I was thinking that for this purpose it might be good to have a global command-line switch that disables human-readable numeric output. There may be more accommodations we should make, but we don't want to go *too* far, because at some level of complexity shell scripting becomes an antipattern.

Discuss.

**Comment by mulkieran** [comment]
Yes. Let's not worry about it now.

**Comment by mulkieran** [comment]
Closing in favor of formatted output issue: #292.
