### ISSUE TITLE
We can generate more user friendly messages from exceptions

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#83]
The only information we have when the exception finally propagates to the top is the exception chain.

We should set up a framework so that other people can contribute code that inspects the error chain and comes up w/ friendlier error messages than what we show now.

**Comment by agrover** [comment]
This seems to lead into supporting localized strings and error messages in the future.

**Comment by mulkieran** [comment]
A first step would be two have a ```rich-error``` flag which would just traverse the exception chain, printing out error messages in turn, as:

```
Error 1: Failed to make stratisd D-Bus connection.
Error 2: The name org.storage.stratis1 was not provided by any .service files
```

or something.

**Comment by mulkieran** [comment]
This gets to seem more urgent, because some of our errors do not have a string representation at all. This is the origin of
"Execution failed:" with no following message stratis response: https://bugzilla.redhat.com/show_bug.cgi?id=1563561.
