### ISSUE TITLE
blockdev list -  displays the UUID of each device

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/stratis-cli#962]
The list commands provide the uuid of each of the objects.  Would it be possible to add the uuids of each of the devices?

[root@sys ~]# stratis pool list
Name            Total / Used / Free    Properties                                   UUID   Alerts
p1     10 GiB / 1.06 GiB / 8.94 GiB   ~Ca,~Cr, Op   820e7e3e-b4cd-459c-a137-85b1876e7ef9   WS001 
[root@sys ~]# stratis fs list
Pool   Filesystem   Total / Used / Free             Created             Device                UUID                                
p1     fs1          1 TiB / 551 MiB / 1023.46 GiB   Feb 23 2023 18:25   /dev/stratis/p1/fs1   acd81b03-fe97-4188-904b-9453079d7f2c
[root@sys ~]# stratis blockdev list
Pool Name   Device Node   Physical Size   Tier
p1          /dev/vdb              5 GiB   DATA
p1          /dev/vdc              5 GiB   DATA

**Comment by mulkieran** [comment]
It would be possible to list the UUIDs of the devices in the output of ```stratis blockdev list```
